### ISSUE TITLE
Add oq-mbtk and VMTK to installer

### ISSUE THREAD

**Issue by antonioettorre** [gem/oq-installers#171]
- [x] add mbtk and vmtk at the installer package 
- [x] add variable to create installer with or without mbtk and vmtk
- [x] add variable to let user to install or not the tools

**Comment by vot4anto** [comment]
https://github.com/gem/oq-builders/pull/174

**Comment by vot4anto** [comment]
https://github.com/gem/oq-builders/pull/175
