### ISSUE TITLE
Uninstall before install is broken when a custom path is used

### ISSUE THREAD

**Issue by daniviga** [gem/oq-installers#29]
If the OQ Engine has not been installed in the standard path `"$PROGRAMFILES${BITNESS}\${PRODUCT_NAME}"` the "uninstall before a new installation" feature does not work.

The problem starts here: https://github.com/gem/oq-installers/blob/master/windows/nsis-installer/win32/installer.nsi#L52
we assume that it's already in the default `$INSTALLDIR`

**Comment by hascar** [comment]
LGTM
