### ISSUE TITLE
DMG installer for Mac (built by Travis)

### ISSUE THREAD

**Issue by daniviga** [gem/oq-installers#40]
For future reference: http://blog.fossasia.org/deploying-a-kivy-application-with-pyinstaller-for-mac-osx-to-github/

**Comment by daniviga** [comment]
Se also http://www.pyinstaller.org/

**Comment by vot4anto** [comment]
https://docs.openquake.org/oq-engine/master/manual/getting-started/installation-instructions/macos.html
